version: '3.4'

services:
  nodemonitor:
    hostname: nodemonitor
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "55001"
      ASPNETCORE_HTTP_PORT: "55000"
      API_URL: nodemonitor:55000
    ports:
      - "55001:55001"
      - "55000:55000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    image: nodemonitor
    container_name: nodemonitor_container
    networks:
      - docker-network

  webui.server:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_HTTP_PORT: "80"
      #ASPNETCORE_Kestrel__Certificates__Default__Password: "eistee"
      #ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/webui.server.pfx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
    image: webuiserver
    container_name: webuiserver_container
    networks:
      - docker-network
      
networks:
  docker-network:
    external: true
