// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DatabaseLib.Models.EntityModels;

namespace DatabaseLib.Migrations
{
    [DbContext(typeof(nmDBContext))]
    partial class nmDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.AbonementEntity", b =>
                {
                    b.Property<int>("AbonementEntityEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AbonementTargetTypEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserFk")
                        .HasColumnType("int");

                    b.HasKey("AbonementEntityEntityId");

                    b.HasIndex("AbonementTargetTypEntityId");

                    b.ToTable("nodemon_Abonement");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.AbonementSourceTypEntity", b =>
                {
                    b.Property<int>("AbonementSourceTypEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbonementSourceTypEntityId");

                    b.ToTable("nodemon_AbonementSourceTyp");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.AbonementTargetTypEntity", b =>
                {
                    b.Property<int>("AbonementTargetTypEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbonementTargetTypEntityId");

                    b.ToTable("nodemon_AbonementTyp");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.AbonementsSourcesEntity", b =>
                {
                    b.Property<int>("AbonementEntityId")
                        .HasColumnType("int");

                    b.Property<int>("AbonementSourceTypEntityId")
                        .HasColumnType("int");

                    b.HasKey("AbonementEntityId", "AbonementSourceTypEntityId");

                    b.HasIndex("AbonementSourceTypEntityId");

                    b.ToTable("nodemon_AbonementsToSources");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.AddrsEntity", b =>
                {
                    b.Property<int>("AddrsEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IfaceEntityIfaceId")
                        .HasColumnType("int");

                    b.Property<int>("IfaceId")
                        .HasColumnType("int");

                    b.HasKey("AddrsEntityId");

                    b.HasIndex("IfaceEntityIfaceId");

                    b.ToTable("nodemon_Addrs");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.FarmEntity", b =>
                {
                    b.Property<int>("FarmEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("IyoOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefixZero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ThreebotId")
                        .HasColumnType("bigint");

                    b.HasKey("FarmEntityId");

                    b.ToTable("nodemon_Farm");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.FarmLocation", b =>
                {
                    b.Property<int>("FarmLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City_farm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Continent_farm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country_farm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FarmEntityId")
                        .HasColumnType("int");

                    b.Property<long>("Latitude_farm")
                        .HasColumnType("bigint");

                    b.Property<long>("Longitude_farm")
                        .HasColumnType("bigint");

                    b.HasKey("FarmLocationId");

                    b.HasIndex("FarmEntityId")
                        .IsUnique();

                    b.ToTable("nodemon_FarmLocation");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.FarmerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IyoOrganization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ThreebotId")
                        .HasColumnType("bigint");

                    b.Property<int?>("WalletAddressesWalletAddressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletAddressesWalletAddressId");

                    b.ToTable("nodemon_Farmer");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.GatewayEntity", b =>
                {
                    b.Property<int>("GatewayEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IfaceEntityIfaceId")
                        .HasColumnType("int");

                    b.Property<int>("IfaceId")
                        .HasColumnType("int");

                    b.HasKey("GatewayEntityId");

                    b.HasIndex("IfaceEntityIfaceId");

                    b.ToTable("nodemon_Gateway");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.IfaceEntity", b =>
                {
                    b.Property<int>("IfaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Macaddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NodeEntityId")
                        .HasColumnType("int");

                    b.HasKey("IfaceId");

                    b.HasIndex("NodeEntityId");

                    b.ToTable("nodemon_Iface");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.NodeEntity", b =>
                {
                    b.Property<int>("NodeEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FarmEntityId")
                        .HasColumnType("int");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<bool>("FreeToUse")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeIdV1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proofs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKeyHex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Uptime")
                        .HasColumnType("datetime2");

                    b.Property<string>("WgPorts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NodeEntityId");

                    b.HasIndex("FarmEntityId");

                    b.ToTable("nodemon_Node");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.NodeHistoryEntity", b =>
                {
                    b.Property<int>("NodeHistoryEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NodeEntityId")
                        .HasColumnType("int");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Uptime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("NodeHistoryEntityId");

                    b.HasIndex("NodeEntityId");

                    b.ToTable("nodemon_NodeHistory");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.NodeLocationEntity", b =>
                {
                    b.Property<int>("NodeLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityNode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContinentNode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryNode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LatitudeNode")
                        .HasColumnType("float");

                    b.Property<double>("LongitudeNode")
                        .HasColumnType("float");

                    b.Property<int>("NodeEntityId")
                        .HasColumnType("int");

                    b.HasKey("NodeLocationId");

                    b.HasIndex("NodeEntityId")
                        .IsUnique();

                    b.ToTable("nodemon_NodeLocation");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.NodeMonSettingsEntity", b =>
                {
                    b.Property<int>("NodeMonSettingsEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NodeMonSettingsEntityId");

                    b.ToTable("nodemon_Settings");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.ReservedResourcesEntity", b =>
                {
                    b.Property<int>("ReservedResourcesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cru")
                        .HasColumnType("bigint");

                    b.Property<long>("Hru")
                        .HasColumnType("bigint");

                    b.Property<long>("Mru")
                        .HasColumnType("bigint");

                    b.Property<int?>("NodeEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("NodeHistoryEntityId")
                        .HasColumnType("int");

                    b.Property<long>("Sru")
                        .HasColumnType("bigint");

                    b.HasKey("ReservedResourcesId");

                    b.HasIndex("NodeEntityId")
                        .IsUnique()
                        .HasFilter("[NodeEntityId] IS NOT NULL");

                    b.HasIndex("NodeHistoryEntityId")
                        .IsUnique()
                        .HasFilter("[NodeHistoryEntityId] IS NOT NULL");

                    b.ToTable("nodemon_ReservedResources");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.ResourcePriceEntity", b =>
                {
                    b.Property<int>("ResourcePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FarmEntityId")
                        .HasColumnType("int");

                    b.Property<long>("Prices")
                        .HasColumnType("bigint");

                    b.HasKey("ResourcePriceId");

                    b.HasIndex("FarmEntityId");

                    b.ToTable("nodemon_ResourcePrice");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.ThreefoldApiUriEntity", b =>
                {
                    b.Property<int>("ThreefoldApiUriEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("List")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThreefoldApiUriEntityId");

                    b.ToTable("nodemon_ThreefoldApiUriList");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.TokenHistoryEntity", b =>
                {
                    b.Property<int>("TokenHistoryEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AmountOfTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("NodeEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PayOutDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TokenHistoryEntityId");

                    b.HasIndex("NodeEntityId");

                    b.ToTable("nodemon_TokenHistory");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.TotalResourcesEntity", b =>
                {
                    b.Property<int>("TotalResourcesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cru")
                        .HasColumnType("bigint");

                    b.Property<long>("Hru")
                        .HasColumnType("bigint");

                    b.Property<long>("Mru")
                        .HasColumnType("bigint");

                    b.Property<int?>("NodeEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("NodeHistoryId")
                        .HasColumnType("int");

                    b.Property<long>("Sru")
                        .HasColumnType("bigint");

                    b.HasKey("TotalResourcesId");

                    b.HasIndex("NodeEntityId")
                        .IsUnique()
                        .HasFilter("[NodeEntityId] IS NOT NULL");

                    b.HasIndex("NodeHistoryId")
                        .IsUnique()
                        .HasFilter("[NodeHistoryId] IS NOT NULL");

                    b.ToTable("nodemon_TotalResources");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.UsedResourcesEntity", b =>
                {
                    b.Property<int>("UsedResourcesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cru")
                        .HasColumnType("bigint");

                    b.Property<long>("Hru")
                        .HasColumnType("bigint");

                    b.Property<long>("Mru")
                        .HasColumnType("bigint");

                    b.Property<int?>("NodeEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("NodeHistoryEntityId")
                        .HasColumnType("int");

                    b.Property<long>("Sru")
                        .HasColumnType("bigint");

                    b.HasKey("UsedResourcesId");

                    b.HasIndex("NodeEntityId")
                        .IsUnique()
                        .HasFilter("[NodeEntityId] IS NOT NULL");

                    b.HasIndex("NodeHistoryEntityId")
                        .IsUnique()
                        .HasFilter("[NodeHistoryEntityId] IS NOT NULL");

                    b.ToTable("nodemon_UsedResources");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.WalletAddressEntity", b =>
                {
                    b.Property<int>("WalletAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FarmEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("FarmerEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("TokenHistoryEntityId")
                        .HasColumnType("int");

                    b.HasKey("WalletAddressId");

                    b.HasIndex("FarmEntityId");

                    b.HasIndex("FarmerEntityId");

                    b.HasIndex("TokenHistoryEntityId");

                    b.ToTable("nodemon_WalletAddress");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.WorkloadsEntity", b =>
                {
                    b.Property<int>("WorkloadsEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Container")
                        .HasColumnType("bigint");

                    b.Property<long>("DelegateDomain")
                        .HasColumnType("bigint");

                    b.Property<long>("K8SVm")
                        .HasColumnType("bigint");

                    b.Property<long>("Network")
                        .HasColumnType("bigint");

                    b.Property<int>("NodeEntityId")
                        .HasColumnType("int");

                    b.Property<long>("Proxy")
                        .HasColumnType("bigint");

                    b.Property<long>("ReverseProxy")
                        .HasColumnType("bigint");

                    b.Property<long>("Subdomain")
                        .HasColumnType("bigint");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<long>("ZdbNamespace")
                        .HasColumnType("bigint");

                    b.HasKey("WorkloadsEntityId");

                    b.HasIndex("NodeEntityId")
                        .IsUnique();

                    b.ToTable("nodemon_Workloads");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.AbonementEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.AbonementTargetTypEntity", "AbonementTargetTyp")
                        .WithMany("Abonements")
                        .HasForeignKey("AbonementTargetTypEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.AbonementsSourcesEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.AbonementEntity", "AbonementEntity")
                        .WithMany("AbonementsSources")
                        .HasForeignKey("AbonementEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NodeMonitor.Models.EntityModels.AbonementSourceTypEntity", "AbonementSourceTyp")
                        .WithMany("AbonementsSources")
                        .HasForeignKey("AbonementSourceTypEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.AddrsEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.IfaceEntity", "IfaceEntity")
                        .WithMany("Addrs")
                        .HasForeignKey("IfaceEntityIfaceId");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.FarmLocation", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.FarmEntity", "FarmEntity")
                        .WithOne("Location")
                        .HasForeignKey("NodeMonitor.Models.EntityModels.FarmLocation", "FarmEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.FarmerEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.WalletAddressEntity", "WalletAddresses")
                        .WithMany()
                        .HasForeignKey("WalletAddressesWalletAddressId");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.GatewayEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.IfaceEntity", "IfaceEntity")
                        .WithMany("Gateway")
                        .HasForeignKey("IfaceEntityIfaceId");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.IfaceEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.NodeEntity", "NodeEntity")
                        .WithMany("Interfaces")
                        .HasForeignKey("NodeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.NodeEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.FarmEntity", "FarmEntity")
                        .WithMany("Nodes")
                        .HasForeignKey("FarmEntityId");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.NodeHistoryEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.NodeEntity", "NodeEntity")
                        .WithMany("NodeHistory")
                        .HasForeignKey("NodeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.NodeLocationEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.NodeEntity", "NodeEntity")
                        .WithOne("NodeLocation")
                        .HasForeignKey("NodeMonitor.Models.EntityModels.NodeLocationEntity", "NodeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.ReservedResourcesEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.NodeEntity", "NodeEntity")
                        .WithOne("ReservedResources")
                        .HasForeignKey("NodeMonitor.Models.EntityModels.ReservedResourcesEntity", "NodeEntityId");

                    b.HasOne("NodeMonitor.Models.EntityModels.NodeHistoryEntity", "NodeHistory")
                        .WithOne("ReservedResources")
                        .HasForeignKey("NodeMonitor.Models.EntityModels.ReservedResourcesEntity", "NodeHistoryEntityId");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.ResourcePriceEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.FarmEntity", "FarmEntity")
                        .WithMany("ResourcePriceCollection")
                        .HasForeignKey("FarmEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.TokenHistoryEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.NodeEntity", "NodeEntity")
                        .WithMany("TokenHistory")
                        .HasForeignKey("NodeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.TotalResourcesEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.NodeEntity", "NodeEntity")
                        .WithOne("TotalResources")
                        .HasForeignKey("NodeMonitor.Models.EntityModels.TotalResourcesEntity", "NodeEntityId");

                    b.HasOne("NodeMonitor.Models.EntityModels.NodeHistoryEntity", "NodeHistory")
                        .WithOne("TotalResources")
                        .HasForeignKey("NodeMonitor.Models.EntityModels.TotalResourcesEntity", "NodeHistoryId");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.UsedResourcesEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.NodeEntity", "NodeEntity")
                        .WithOne("UsedResources")
                        .HasForeignKey("NodeMonitor.Models.EntityModels.UsedResourcesEntity", "NodeEntityId");

                    b.HasOne("NodeMonitor.Models.EntityModels.NodeHistoryEntity", "NodeHistory")
                        .WithOne("UsedResources")
                        .HasForeignKey("NodeMonitor.Models.EntityModels.UsedResourcesEntity", "NodeHistoryEntityId");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.WalletAddressEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.FarmEntity", "FarmEntity")
                        .WithMany("WalletAddressesCollection")
                        .HasForeignKey("FarmEntityId");

                    b.HasOne("NodeMonitor.Models.EntityModels.FarmerEntity", null)
                        .WithMany("WalletAddressesCollection")
                        .HasForeignKey("FarmerEntityId");

                    b.HasOne("NodeMonitor.Models.EntityModels.TokenHistoryEntity", "TokenHistoryEntity")
                        .WithMany("WalletAddress")
                        .HasForeignKey("TokenHistoryEntityId");
                });

            modelBuilder.Entity("NodeMonitor.Models.EntityModels.WorkloadsEntity", b =>
                {
                    b.HasOne("NodeMonitor.Models.EntityModels.NodeEntity", "NodeEntity")
                        .WithOne("Workloads")
                        .HasForeignKey("NodeMonitor.Models.EntityModels.WorkloadsEntity", "NodeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
